<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zkrv9U4' shared service.

return $this->privates['.service_locator.zkrv9U4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AuthentificationController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\AuthentificationController::update' => ['privates', '.service_locator.nk9g.Cv', 'get_ServiceLocator_Nk9g_CvService.php', true],
    'App\\Controller\\CompteController::Add' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController::Add' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\AuthentificationController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\AuthentificationController:update' => ['privates', '.service_locator.nk9g.Cv', 'get_ServiceLocator_Nk9g_CvService.php', true],
    'App\\Controller\\CompteController:Add' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController:Add' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
], [
    'App\\Controller\\AuthentificationController::register' => '?',
    'App\\Controller\\AuthentificationController::update' => '?',
    'App\\Controller\\CompteController::Add' => '?',
    'App\\Controller\\PartenaireController::Add' => '?',
    'App\\Controller\\AuthentificationController:register' => '?',
    'App\\Controller\\AuthentificationController:update' => '?',
    'App\\Controller\\CompteController:Add' => '?',
    'App\\Controller\\PartenaireController:Add' => '?',
]);
