<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Xe13BTv' shared service.

return $this->privates['.service_locator.Xe13BTv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'utilisateur' => ['privates', '.errored..service_locator.Xe13BTv.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.Xe13BTv": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
    'validateur' => ['services', 'validator', 'getValidatorService', false],
], [
    'entityManager' => '?',
    'serializer' => '?',
    'utilisateur' => 'App\\Entity\\Utilisateur',
    'validateur' => '?',
]);
