<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventSubscriber\ExeptionSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/EventSubscriber/ExeptionSubscriber.php';

return $this->privates['App\\EventSubscriber\\ExeptionSubscriber'] = new \App\EventSubscriber\ExeptionSubscriber();
