<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..Mcpt2h' shared service.

return $this->privates['.service_locator..Mcpt2h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AuthentificationController::modif' => ['privates', '.service_locator.Xe13BTv', 'get_ServiceLocator_Xe13BTvService.php', true],
    'App\\Controller\\AuthentificationController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\CompteController::modif' => ['privates', '.service_locator.q5NLX8c', 'get_ServiceLocator_Q5NLX8cService.php', true],
    'App\\Controller\\CompteController::new' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController::Add' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\AuthentificationController:modif' => ['privates', '.service_locator.Xe13BTv', 'get_ServiceLocator_Xe13BTvService.php', true],
    'App\\Controller\\AuthentificationController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\CompteController:modif' => ['privates', '.service_locator.q5NLX8c', 'get_ServiceLocator_Q5NLX8cService.php', true],
    'App\\Controller\\CompteController:new' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController:Add' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
], [
    'App\\Controller\\AuthentificationController::modif' => '?',
    'App\\Controller\\AuthentificationController::register' => '?',
    'App\\Controller\\CompteController::modif' => '?',
    'App\\Controller\\CompteController::new' => '?',
    'App\\Controller\\PartenaireController::Add' => '?',
    'App\\Controller\\AuthentificationController:modif' => '?',
    'App\\Controller\\AuthentificationController:register' => '?',
    'App\\Controller\\CompteController:modif' => '?',
    'App\\Controller\\CompteController:new' => '?',
    'App\\Controller\\PartenaireController:Add' => '?',
]);
