<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.q5NLX8c' shared service.

return $this->privates['.service_locator.q5NLX8c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'compte' => ['privates', '.errored..service_locator.q5NLX8c.App\\Entity\\Compte', NULL, 'Cannot autowire service ".service_locator.q5NLX8c": it references class "App\\Entity\\Compte" but no such service exists.'],
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'validateur' => ['services', 'validator', 'getValidatorService', false],
], [
    'compte' => 'App\\Entity\\Compte',
    'entityManager' => '?',
    'serializer' => '?',
    'validateur' => '?',
]);
